services:
  db:
    image: postgres:15
    container_name: coco_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coco_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - coco-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d coco_db"]
      interval: 30s
      timeout: 10s
      retries: 5
  api:
    build: .
    container_name: coco_api
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: taskapi_user
      DB_PASSWORD: password
      DB_NAME: coco_db
      DB_SSLMODE: disable
      SERVER_PORT: 9000
      APP_ENV: production
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - coco-network

volumes:
  pgdata:

networks:
  coco-network:
    driver: bridge
